In [26]:
from sklearn.neighbors import NearestNeighbors
import numpy as np

In [46]:
# X为6个点的数据
X = np.array([[3, 2], [-2, -1], [-1, -1], [1, 1], [2, 1], [3, 2]])

In [47]:
# 以 X[i] 为参考点，找(n_neighbors - 1)个与之最近的点
nbrs = NearestNeighbors(n_neighbors = 3 , algorithm = 'ball_tree').fit(X)

In [48]:
# 返回值 indices 第0列元素为参考点的索引，后面是(n_neighbors - 1)个与之最近的点的索引
# 返回值 distances 第0列元素为与自身的距离，后面是(n_neighbors - 1)个与之最近的点与参考点的距离
distances, indices = nbrs.kneighbors(X)

In [49]:
indices

array([[0, 5, 4],
       [1, 2, 3],
       [2, 1, 3],
       [3, 4, 0],
       [4, 3, 0],
       [0, 5, 4]], dtype=int64)

In [50]:
distances

array([[ 0.        ,  0.        ,  1.41421356],
       [ 0.        ,  1.        ,  3.60555128],
       [ 0.        ,  1.        ,  2.82842712],
       [ 0.        ,  1.        ,  2.23606798],
       [ 0.        ,  1.        ,  1.41421356],
       [ 0.        ,  0.        ,  1.41421356]])

In [51]:
#输出的是求解n个最近邻点后的矩阵图，1表示是最近点，0表示不是最近点
print (nbrs.kneighbors_graph(X).toarray())

[[ 1.  0.  0.  0.  1.  1.]
 [ 0.  1.  1.  1.  0.  0.]
 [ 0.  1.  1.  1.  0.  0.]
 [ 1.  0.  0.  1.  1.  0.]
 [ 1.  0.  0.  1.  1.  0.]
 [ 1.  0.  0.  0.  1.  1.]]
